server:
  port: 8885

spring:
  application:
    name: gassman-payment-service
  rabbitmq:
    addresses:
  cloud:
    stream:
      bindings:
        orderPaymentChannel:
          destination: gassman-order-payment

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

paypal:
  clientId:
  clientSecret: 
