server:
  port: 8885

spring:
  application:
    name: gassman-payment-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/gassman-payment
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    username: root
    password:

  rabbitmq:
    addresses: amqp://***
  cloud:
    stream:
      bindings:
        orderPaymentChannel:
          destination: gassman-order-payment
        rechargeUserCreditChannel:
          destination: gassman-recharge-user-credit

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

paypal:
  clientId: YOUR_CLIENT_ID
  clientSecret: YOUR_SECRET
